apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: projeto-fiap-pod
spec:
  replicas: 1
  template:
    metadata:
      name: projeto-fiap-pod
      labels: 
        app: projeto-fiap-pod
    spec:
      containers:
        - name: projeto-fiap-container
          image: 'grupo27/techchallengefood:3.0'
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-configmap    
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html#/produto-controller/listar
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 10m    
  selector:
    matchLabels:
      app: projeto-fiap-pod