apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: projeto-fiap-pod
spec:
  replicas: 1
  template:
    metadata:
      name: projeto-fiap-pod
      labels: 
        app: projeto-fiap-pod
    spec:
      containers:
        - name: projeto-fiap-container
          image: 'grupo27/techchallengefood:5.0'
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-configmap    
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html#/produto-controller/listar
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"    
  selector:
    matchLabels:
      app: projeto-fiap-pod
