version: '3.9'

volumes:
  mysql_data: {}

services:
  mysql:
    image: mysql:8.0
    volumes:
       - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '172.18.0.1'
      MYSQL_DATABASE: techchallengefood
      MYSQL_USER: techchallengefood
      MYSQL_PASSWORD: techchallengefood
  java:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      JAVA_DB_HOST: mysql:3306
      JAVA_DB_USER: techchallengefood
      JAVA_DB_PASSWORD: techchallengefood
      JAVA_DB_NAME: techchallengefood
    volumes: 
      - /app/sprin-app.jar
