apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
 spring.datasource.url: jdbc:mysql://db_techfood:3306/db_techfood
 spring.datasource.username: root
 spring.datasource.password: root
 spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
