apiVersion: v1
kind: Pod
metadata:
  name: db-techfood
  labels: 
    app: db-techfood
spec:
  containers:
    - name: db-techfood-container
      image: mysql
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
      
