services:
  db_techfood:
    container_name: db_techfood
    image: mysql
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_DATABASE: db_techfood
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      foodtechchallenge-net:

  foodtechchallenge-webservices:
    container_name: foodtechchallenge-webservices
    build:
      # context: food-techchallenge-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db_techfood
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://db_techfood:3306/db_techfood
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      foodtechchallenge-net:
    restart: on-failure

networks:
  foodtechchallenge-net: