apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
spec:
  replicas: 1
  template:
    metadata:
      name: projeto-fiap-pod
      labels: 
        app: projeto-fiap-pod
    spec:
      containers:
        - name: projeto-fiap-container
          image: 'grupo27/techchallengefood:1.0'
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: db-configmap         
  selector:
    matchLabels:
      app: projeto-fiap-pod