apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: projeto-fiap-pod
spec:
  replicas: 1
  template:
    metadata:
      name: projeto-fiap-pod
      labels: 
        app: projeto-fiap-pod
    spec:
      containers:
        - name: projeto-fiap-container
          image: 'grupo27/techchallengefood:3.0'
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-configmap        
  selector:
    matchLabels:
      app: projeto-fiap-pod