apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db
  labels:
    app: db-projeto-fiap
spec:
  replicas: 1
  template:
    metadata:
      name: db-projeto-fiap
      labels: 
        app: db-projeto-fiap
    spec:
      containers:
        - name: db-projeto-fiap-container
          image: mysql
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-projeto-fiap